### ISSUE TITLE
Handle "Special device does not exist"

### ISSUE THREAD

**Issue by BentonEdmondson** [samuela/nixos-up#8]
I got the "Special device does not exist" that you explained [here](https://github.com/samuela/nixos-up/blob/main/nixos-up.ml#L216). As explained in your comment, I simply ran `blockdev --rereadpt /dev/mydude` and then reran your command and everything worked thenceforth.

Is there a reason you can't detect this error with a try-catch or something and then run the above command automatically and then continue? Or at the very least can you tell the user to run the command themself?

**Comment by BentonEdmondson** [comment]
Actually, I just realized that it was running every time before you commented it out. What's wrong with having it run every time if it just tells the system to acknowledge the partition changes?

**Comment by samuela** [comment]
This is a really weird error that I have not been able to get to the bottom of. I previously had that in there, but it turns out I still randomly got this error once in a while. Running on the same hardware and everything... So I'm at a loss for what exactly is causing this. I came to the conclusion that `blockdev` was possibly unrelated, and at best only correlated with fixing the underlying issue. 

If you or anyone else has any insights here please let me know!

**Comment by samuela** [comment]
https://serverfault.com/questions/36038/reread-partition-table-without-rebooting looks relevant. Unfortunately no solution is reported as 100% effective.

**Comment by samuela** [comment]
This should be fixed in https://github.com/samuela/nixos-up/commit/525a5cefd676d8686adf08bb4a49294f8a1df7c5. I (begrudgingly) did a complete rewrite in python. Along the way I added some logic to try re-reading the partition table and wait until the right things become available before proceeding with the install. I think it should resolve this issue.

If it comes up again, def let me know!
